
package azure
import (
	"github.com/kaytu-io/kaytu-azure-describer/azure/describer"
	"github.com/kaytu-io/kaytu-util/pkg/source"
)
var resourceTypes = map[string]ResourceType{

	"Microsoft.App/containerApps": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.App/containerApps",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.AppContainerApps),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.App/managedEnvironments": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.App/managedEnvironments",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.AppManagedEnvironment),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Blueprint/blueprints": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Blueprint/blueprints",
		ResourceLabel:        "",
		ServiceName:          "Blueprint",
		ListDescriber:        DescribeBySubscription(describer.BlueprintBlueprint),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Cdn/profiles": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Cdn/profiles",
		ResourceLabel:        "",
		ServiceName:          "Cdn",
		ListDescriber:        DescribeBySubscription(describer.CdnProfiles),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Compute/cloudServices": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/cloudServices",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeCloudServices),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.ContainerInstance/containerGroups": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.ContainerInstance/containerGroups",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ContainerInstanceContainerGroups),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.DataMigration/services": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DataMigration/services",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.DataMigrationServices),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.DataProtection/backupVaults": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DataProtection/backupVaults",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.DataProtectionBackupVaults),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.DataProtection/backupVaults/backupPolicies": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DataProtection/backupVaults/backupPolicies",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.DataProtectionBackupVaultsBackupPolicies),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Logic/integrationAccounts": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Logic/integrationAccounts",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.LogicIntegrationAccounts),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/bastionHosts": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/bastionHosts",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.NetworkBastionHosts),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/connections": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/connections",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.NetworkConnections),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/firewallPolicies": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/firewallPolicies",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.FirewallPolicy),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/localNetworkGateways": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/localNetworkGateways",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.LocalNetworkGateway),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/privateLinkServices": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/privateLinkServices",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.PrivateLinkService),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/publicIPPrefixes": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/publicIPPrefixes",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.PublicIPPrefix),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/virtualHubs": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/virtualHubs",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.NetworkVirtualHubs),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/virtualWans": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/virtualWans",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.NetworkVirtualWans),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/vpnGateways": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/vpnGateways",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.VpnGateway),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/vpnGateways/vpnConnections": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/vpnGateways/vpnConnections",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.NetworkVpnGatewaysVpnConnections),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/vpnSites": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/vpnSites",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.NetworkVpnGatewaysVpnSites),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.OperationalInsights/workspaces": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.OperationalInsights/workspaces",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.OperationalInsightsWorkspaces),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.StreamAnalytics/cluster": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.StreamAnalytics/cluster",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.StreamAnalyticsCluster),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.TimeSeriesInsights/environments": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.TimeSeriesInsights/environments",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.TimeSeriesInsightsEnvironments),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.VirtualMachineImages/imageTemplates": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.VirtualMachineImages/imageTemplates",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.VirtualMachineImagesImageTemplates),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Web/serverFarms": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Web/serverFarms",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.WebServerFarms),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Compute/virtualMachineScaleSets/virtualMachines": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/virtualMachineScaleSets/virtualMachines",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeVirtualMachineScaleSetVm),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Automation/automationAccounts": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Automation/automationAccounts",
		ResourceLabel:        "",
		ServiceName:          "Automation",
		ListDescriber:        DescribeBySubscription(describer.AutomationAccounts),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Network/dnsZones": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/dnsZones",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.DNSZones),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Databricks/workspaces": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Databricks/workspaces",
		ResourceLabel:        "",
		ServiceName:          "Databricks",
		ListDescriber:        DescribeBySubscription(describer.DatabricksWorkspaces),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Network/privateDnsZones": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/privateDnsZones",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.PrivateDnsZones),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Network/privateEndpoints": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/privateEndpoints",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.PrivateEndpoints),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.EventGrid/domains/topics": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.EventGrid/domains/topics",
		ResourceLabel:        "",
		ServiceName:          "EventGrid",
		ListDescriber:        DescribeBySubscription(describer.EventGridDomainTopic),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_eventgrid_domain_topic"},
		TerraformServiceName: "eventgrid",
		FastDiscovery: false,
	},

	"Microsoft.Network/networkWatchers": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/networkWatchers",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.NetworkWatcher),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_network_watcher"},
		TerraformServiceName: "network",
		FastDiscovery: false,
	},

	"Microsoft.Resources/resourceGroups": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Resources/resourceGroups",
		ResourceLabel:        "",
		ServiceName:          "Resources",
		ListDescriber:        DescribeBySubscription(describer.ResourceGroup),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_resource_group"},
		TerraformServiceName: "resource",
		FastDiscovery: true,
	},

	"Microsoft.Web/staticSites": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Web/staticSites",
		ResourceLabel:        "",
		ServiceName:          "Web",
		ListDescriber:        DescribeBySubscription(describer.AppServiceWebApp),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_linux_web_app","azurerm_windows_web_app"},
		TerraformServiceName: "appservice",
		FastDiscovery: false,
	},

	"Microsoft.Resources/serviceprincipals": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Resources/serviceprincipals",
		ResourceLabel:        "",
		ServiceName:          "Resources",
		ListDescriber:        DescribeADByTenantID(describer.AdServicePrinciple),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.CognitiveServices/accounts": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.CognitiveServices/accounts",
		ResourceLabel:        "",
		ServiceName:          "CognitiveServices",
		ListDescriber:        DescribeBySubscription(describer.CognitiveAccount),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_cognitive_account"},
		TerraformServiceName: "cognitive",
		FastDiscovery: false,
	},

	"Microsoft.Sql/managedInstances": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Sql/managedInstances",
		ResourceLabel:        "",
		ServiceName:          "Sql",
		ListDescriber:        DescribeBySubscription(describer.MssqlManagedInstance),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_mssql_managed_instance"},
		TerraformServiceName: "mssql",
		FastDiscovery: true,
	},

	"Microsoft.Sql/virtualclusters": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Sql/virtualclusters",
		ResourceLabel:        "",
		ServiceName:          "Sql",
		ListDescriber:        DescribeBySubscription(describer.SqlVirtualClusters),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Sql/managedInstances/databases": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Sql/managedInstances/databases",
		ResourceLabel:        "",
		ServiceName:          "Sql",
		ListDescriber:        DescribeBySubscription(describer.MssqlManagedInstanceDatabases),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Sql/servers/databases": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Sql/servers/databases",
		ResourceLabel:        "",
		ServiceName:          "Sql",
		ListDescriber:        DescribeBySubscription(describer.SqlDatabase),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_sql_database"},
		TerraformServiceName: "sql",
		FastDiscovery: true,
	},

	"Microsoft.Storage/fileShares": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Storage/fileShares",
		ResourceLabel:        "",
		ServiceName:          "Storage",
		ListDescriber:        DescribeBySubscription(describer.StorageFileShare),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_storage_share_file"},
		TerraformServiceName: "storage",
		FastDiscovery: false,
	},

	"Microsoft.DBforPostgreSQL/servers": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DBforPostgreSQL/servers",
		ResourceLabel:        "",
		ServiceName:          "DBforPostgreSQL",
		ListDescriber:        DescribeBySubscription(describer.PostgresqlServer),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_postgresql_server"},
		TerraformServiceName: "postgres",
		FastDiscovery: true,
	},

	"Microsoft.DBforPostgreSQL/flexibleservers": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DBforPostgreSQL/flexibleservers",
		ResourceLabel:        "",
		ServiceName:          "DBforPostgreSQL",
		ListDescriber:        DescribeBySubscription(describer.PostgresqlFlexibleservers),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.AnalysisServices/servers": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.AnalysisServices/servers",
		ResourceLabel:        "",
		ServiceName:          "AnalysisServices",
		ListDescriber:        DescribeBySubscription(describer.AnalysisService),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Security/pricings": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Security/pricings",
		ResourceLabel:        "",
		ServiceName:          "Security",
		ListDescriber:        DescribeBySubscription(describer.SecurityCenterSubscriptionPricing),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_security_center_subscription_pricing"},
		TerraformServiceName: "securitycenter",
		FastDiscovery: false,
	},

	"Microsoft.Insights/guestDiagnosticSettings": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Insights/guestDiagnosticSettings",
		ResourceLabel:        "",
		ServiceName:          "Insights",
		ListDescriber:        DescribeBySubscription(describer.DiagnosticSetting),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Resources/groups": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Resources/groups",
		ResourceLabel:        "",
		ServiceName:          "Resources",
		ListDescriber:        DescribeADByTenantID(describer.AdGroup),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Web/hostingEnvironments": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Web/hostingEnvironments",
		ResourceLabel:        "",
		ServiceName:          "Web",
		ListDescriber:        DescribeBySubscription(describer.AppServiceEnvironment),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_app_service_environment"},
		TerraformServiceName: "web",
		FastDiscovery: false,
	},

	"Microsoft.Cache/redis": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Cache/redis",
		ResourceLabel:        "",
		ServiceName:          "Cache",
		ListDescriber:        DescribeBySubscription(describer.RedisCache),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_redis_cache"},
		TerraformServiceName: "redis",
		FastDiscovery: true,
	},

	"Microsoft.ContainerRegistry/registries": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.ContainerRegistry/registries",
		ResourceLabel:        "",
		ServiceName:          "ContainerRegistry",
		ListDescriber:        DescribeBySubscription(describer.ContainerRegistry),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_container_registry"},
		TerraformServiceName: "containers",
		FastDiscovery: true,
	},

	"Microsoft.DataFactory/factoriesPipelines": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DataFactory/factoriesPipelines",
		ResourceLabel:        "",
		ServiceName:          "DataFactory",
		ListDescriber:        DescribeBySubscription(describer.DataFactoryPipeline),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_data_factory_pipeline"},
		TerraformServiceName: "datafactory",
		FastDiscovery: false,
	},

	"Microsoft.Compute/resourceSku": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/resourceSku",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeResourceSKU),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/expressRouteCircuits": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/expressRouteCircuits",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.ExpressRouteCircuit),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_express_route_circuit"},
		TerraformServiceName: "network",
		FastDiscovery: false,
	},

	"Microsoft.Management/groups": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Management/groups",
		ResourceLabel:        "",
		ServiceName:          "Management",
		ListDescriber:        DescribeBySubscription(describer.ManagementGroup),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_management_group"},
		TerraformServiceName: "managementgroup",
		FastDiscovery: false,
	},

	"Microsoft.Sql/virtualMachines": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Sql/virtualMachines",
		ResourceLabel:        "",
		ServiceName:          "Sql",
		ListDescriber:        DescribeBySubscription(describer.SqlServerVirtualMachine),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Sql/virtualMachineGroups": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Sql/virtualMachineGroups",
		ResourceLabel:        "",
		ServiceName:          "Sql",
		ListDescriber:        DescribeBySubscription(describer.SqlServerVirtualMachineGroups),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Storage/tableServices": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Storage/tableServices",
		ResourceLabel:        "",
		ServiceName:          "Storage",
		ListDescriber:        DescribeBySubscription(describer.StorageTableService),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Synapse/workspaces": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Synapse/workspaces",
		ResourceLabel:        "",
		ServiceName:          "Synapse",
		ListDescriber:        DescribeBySubscription(describer.SynapseWorkspace),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_synapse_workspace"},
		TerraformServiceName: "synapse",
		FastDiscovery: false,
	},

	"Microsoft.Synapse/workspaces/bigdatapools": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Synapse/workspaces/bigdatapools",
		ResourceLabel:        "",
		ServiceName:          "Synapse",
		ListDescriber:        DescribeBySubscription(describer.SynapseWorkspaceBigdataPools),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Synapse/workspaces/sqlpools": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Synapse/workspaces/sqlpools",
		ResourceLabel:        "",
		ServiceName:          "Synapse",
		ListDescriber:        DescribeBySubscription(describer.SynapseWorkspaceSqlpools),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.StreamAnalytics/streamingJobs": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.StreamAnalytics/streamingJobs",
		ResourceLabel:        "",
		ServiceName:          "StreamAnalytics",
		ListDescriber:        DescribeBySubscription(describer.StreamAnalyticsJob),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_stream_analytics_job"},
		TerraformServiceName: "streamanalytics",
		FastDiscovery: false,
	},

	"Microsoft.CostManagement/CostBySubscription": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.CostManagement/CostBySubscription",
		ResourceLabel:        "",
		ServiceName:          "CostManagement",
		ListDescriber:        DescribeBySubscription(describer.DailyCostBySubscription),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.ContainerService/managedClusters": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.ContainerService/managedClusters",
		ResourceLabel:        "",
		ServiceName:          "ContainerService",
		ListDescriber:        DescribeBySubscription(describer.KubernetesCluster),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_kubernetes_cluster"},
		TerraformServiceName: "containers",
		FastDiscovery: true,
	},

	"Microsoft.DataFactory/factories": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DataFactory/factories",
		ResourceLabel:        "",
		ServiceName:          "DataFactory",
		ListDescriber:        DescribeBySubscription(describer.DataFactory),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_data_factory"},
		TerraformServiceName: "datafactory",
		FastDiscovery: false,
	},

	"Microsoft.Sql/servers": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Sql/servers",
		ResourceLabel:        "",
		ServiceName:          "Sql",
		ListDescriber:        DescribeBySubscription(describer.SqlServer),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_sql_server"},
		TerraformServiceName: "sql",
		FastDiscovery: true,
	},

	"Microsoft.Sql/servers/jobagents": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Sql/servers/jobagents",
		ResourceLabel:        "",
		ServiceName:          "Sql",
		ListDescriber:        DescribeBySubscription(describer.SqlServerJobAgents),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Security/autoProvisioningSettings": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Security/autoProvisioningSettings",
		ResourceLabel:        "",
		ServiceName:          "Security",
		ListDescriber:        DescribeBySubscription(describer.SecurityCenterAutoProvisioning),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_security_center_auto_provisioning"},
		TerraformServiceName: "securitycenter",
		FastDiscovery: false,
	},

	"Microsoft.Insights/logProfiles": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Insights/logProfiles",
		ResourceLabel:        "",
		ServiceName:          "Insights",
		ListDescriber:        DescribeBySubscription(describer.LogProfile),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.DataBoxEdge/dataBoxEdgeDevices": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DataBoxEdge/dataBoxEdgeDevices",
		ResourceLabel:        "",
		ServiceName:          "DataBoxEdge",
		ListDescriber:        DescribeBySubscription(describer.DataboxEdgeDevice),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_databox_edge_device"},
		TerraformServiceName: "databoxedge",
		FastDiscovery: false,
	},

	"Microsoft.Network/loadBalancers": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/loadBalancers",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.LoadBalancer),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_lb"},
		TerraformServiceName: "loadbalancer",
		FastDiscovery: true,
	},

	"Microsoft.Network/azureFirewalls": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/azureFirewalls",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.NetworkAzureFirewall),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_firewall"},
		TerraformServiceName: "firewall",
		FastDiscovery: true,
	},

	"Microsoft.Management/locks": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Management/locks",
		ResourceLabel:        "",
		ServiceName:          "Management",
		ListDescriber:        DescribeBySubscription(describer.ManagementLock),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Compute/virtualMachineScaleSets/networkInterfaces": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/virtualMachineScaleSets/networkInterfaces",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeVirtualMachineScaleSetNetworkInterface),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/frontDoors": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/frontDoors",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.FrontDoor),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_frontdoor"},
		TerraformServiceName: "frontdoor",
		FastDiscovery: true,
	},

	"Microsoft.Authorization/policyAssignments": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Authorization/policyAssignments",
		ResourceLabel:        "",
		ServiceName:          "Authorization",
		ListDescriber:        DescribeBySubscription(describer.PolicyAssignment),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Search/searchServices": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Search/searchServices",
		ResourceLabel:        "",
		ServiceName:          "Search",
		ListDescriber:        DescribeBySubscription(describer.SearchService),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_search_service"},
		TerraformServiceName: "search",
		FastDiscovery: false,
	},

	"Microsoft.Security/settings": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Security/settings",
		ResourceLabel:        "",
		ServiceName:          "Security",
		ListDescriber:        DescribeBySubscription(describer.SecurityCenterSetting),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_security_center_setting"},
		TerraformServiceName: "securitycenter",
		FastDiscovery: false,
	},

	"Microsoft.RecoveryServices/vaults": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.RecoveryServices/vaults",
		ResourceLabel:        "",
		ServiceName:          "RecoveryServices",
		ListDescriber:        DescribeBySubscription(describer.RecoveryServicesVault),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_recovery_services_vault"},
		TerraformServiceName: "recoveryservices",
		FastDiscovery: false,
	},

	"Microsoft.Compute/diskEncryptionSets": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/diskEncryptionSets",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeDiskEncryptionSet),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_disk_encryption_set"},
		TerraformServiceName: "compute",
		FastDiscovery: true,
	},

	"Microsoft.DocumentDB/SqlDatabases": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DocumentDB/SqlDatabases",
		ResourceLabel:        "",
		ServiceName:          "DocumentDB",
		ListDescriber:        DescribeBySubscription(describer.DocumentDBSQLDatabase),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_cosmosdb_sql_database"},
		TerraformServiceName: "cosmos",
		FastDiscovery: true,
	},

	"Microsoft.EventGrid/topics": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.EventGrid/topics",
		ResourceLabel:        "",
		ServiceName:          "EventGrid",
		ListDescriber:        DescribeBySubscription(describer.EventGridTopic),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_eventgrid_topic"},
		TerraformServiceName: "eventgrid",
		FastDiscovery: false,
	},

	"Microsoft.EventHub/namespaces": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.EventHub/namespaces",
		ResourceLabel:        "",
		ServiceName:          "EventHub",
		ListDescriber:        DescribeBySubscription(describer.EventhubNamespace),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_eventhub_namespace"},
		TerraformServiceName: "eventhub",
		FastDiscovery: true,
	},

	"Microsoft.EventHub/namespaces/eventHubs": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.EventHub/namespaces/eventHubs",
		ResourceLabel:        "",
		ServiceName:          "EventHub",
		ListDescriber:        DescribeBySubscription(describer.EventhubNamespaceEventhub),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_eventhub_namespace"},
		TerraformServiceName: "eventhub",
		FastDiscovery: true,
	},

	"Microsoft.MachineLearningServices/workspaces": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.MachineLearningServices/workspaces",
		ResourceLabel:        "",
		ServiceName:          "MachineLearningServices",
		ListDescriber:        DescribeBySubscription(describer.MachineLearningWorkspace),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_machine_learning_workspace"},
		TerraformServiceName: "machinelearning",
		FastDiscovery: false,
	},

	"Microsoft.CostManagement/CostByResourceType": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.CostManagement/CostByResourceType",
		ResourceLabel:        "",
		ServiceName:          "CostManagement",
		ListDescriber:        DescribeBySubscription(describer.DailyCostByResourceType),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/networkInterfaces": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/networkInterfaces",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.NetworkInterface),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_network_interface"},
		TerraformServiceName: "network",
		FastDiscovery: true,
	},

	"Microsoft.Network/publicIPAddresses": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/publicIPAddresses",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.PublicIPAddress),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_public_ip"},
		TerraformServiceName: "network",
		FastDiscovery: false,
	},

	"Microsoft.HealthcareApis/services": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.HealthcareApis/services",
		ResourceLabel:        "",
		ServiceName:          "HealthcareApis",
		ListDescriber:        DescribeBySubscription(describer.HealthcareService),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_healthcare_service"},
		TerraformServiceName: "healthcare",
		FastDiscovery: false,
	},

	"Microsoft.ServiceBus/namespaces": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.ServiceBus/namespaces",
		ResourceLabel:        "",
		ServiceName:          "ServiceBus",
		ListDescriber:        DescribeBySubscription(describer.ServicebusNamespace),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_servicebus_namespace"},
		TerraformServiceName: "servicebus",
		FastDiscovery: false,
	},

	"Microsoft.Web/sites": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Web/sites",
		ResourceLabel:        "",
		ServiceName:          "Web",
		ListDescriber:        DescribeBySubscription(describer.AppServiceFunctionApp),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_function_app"},
		TerraformServiceName: "web",
		FastDiscovery: true,
	},

	"Microsoft.Compute/availabilitySets": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/availabilitySets",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeAvailabilitySet),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_availability_set"},
		TerraformServiceName: "compute",
		FastDiscovery: true,
	},

	"Microsoft.Network/virtualNetworks": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/virtualNetworks",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.VirtualNetwork),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_virtual_network"},
		TerraformServiceName: "network",
		FastDiscovery: true,
	},

	"Microsoft.Security/securityContacts": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Security/securityContacts",
		ResourceLabel:        "",
		ServiceName:          "Security",
		ListDescriber:        DescribeBySubscription(describer.SecurityCenterContact),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_security_center_contact"},
		TerraformServiceName: "securitycenter",
		FastDiscovery: false,
	},

	"Microsoft.Compute/diskswriteops": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/diskswriteops",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeDiskWriteOps),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Compute/diskswriteopshourly": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/diskswriteopshourly",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeDiskWriteOpsHourly),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.EventGrid/domains": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.EventGrid/domains",
		ResourceLabel:        "",
		ServiceName:          "EventGrid",
		ListDescriber:        DescribeBySubscription(describer.EventGridDomain),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_eventgrid_domain"},
		TerraformServiceName: "eventgrid",
		FastDiscovery: false,
	},

	"Microsoft.KeyVault/deletedVaults": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.KeyVault/deletedVaults",
		ResourceLabel:        "",
		ServiceName:          "KeyVault",
		ListDescriber:        DescribeBySubscription(describer.DeletedVault),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Storage/tables": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Storage/tables",
		ResourceLabel:        "",
		ServiceName:          "Storage",
		ListDescriber:        DescribeBySubscription(describer.StorageTable),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_storage_table"},
		TerraformServiceName: "storage",
		FastDiscovery: false,
	},

	"Microsoft.Resources/users": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Resources/users",
		ResourceLabel:        "",
		ServiceName:          "Resources",
		ListDescriber:        DescribeADByTenantID(describer.AdUsers),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Compute/snapshots": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/snapshots",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeSnapshots),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_snapshot"},
		TerraformServiceName: "compute",
		FastDiscovery: true,
	},

	"Microsoft.Kusto/clusters": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Kusto/clusters",
		ResourceLabel:        "",
		ServiceName:          "Kusto",
		ListDescriber:        DescribeBySubscription(describer.KustoCluster),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_kusto_cluster"},
		TerraformServiceName: "kusto",
		FastDiscovery: false,
	},

	"Microsoft.StorageSync/storageSyncServices": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.StorageSync/storageSyncServices",
		ResourceLabel:        "",
		ServiceName:          "StorageSync",
		ListDescriber:        DescribeBySubscription(describer.StorageSync),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_storage_sync"},
		TerraformServiceName: "storage",
		FastDiscovery: false,
	},

	"Microsoft.Security/locations/jitNetworkAccessPolicies": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Security/locations/jitNetworkAccessPolicies",
		ResourceLabel:        "",
		ServiceName:          "Security",
		ListDescriber:        DescribeBySubscription(describer.SecurityCenterJitNetworkAccessPolicy),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/virtualNetworks/subnets": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/virtualNetworks/subnets",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.Subnet),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_subnet"},
		TerraformServiceName: "network",
		FastDiscovery: true,
	},

	"Microsoft.LoadBalancer/backendAddressPools": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.LoadBalancer/backendAddressPools",
		ResourceLabel:        "",
		ServiceName:          "LoadBalancer",
		ListDescriber:        DescribeBySubscription(describer.LoadBalancerBackendAddressPool),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_lb_backend_address_pool"},
		TerraformServiceName: "loadbalancer",
		FastDiscovery: false,
	},

	"Microsoft.Network/loadBalancers/loadBalancingRules": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/loadBalancers/loadBalancingRules",
		ResourceLabel:        "",
		ServiceName:          "LoadBalancer",
		ListDescriber:        DescribeBySubscription(describer.LoadBalancerRule),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_lb_rule"},
		TerraformServiceName: "loadbalancer",
		FastDiscovery: false,
	},

	"Microsoft.Compute/virtualMachineCpuUtilizationDaily": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/virtualMachineCpuUtilizationDaily",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeVirtualMachineCpuUtilizationDaily),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.DataLakeStore/accounts": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DataLakeStore/accounts",
		ResourceLabel:        "",
		ServiceName:          "DataLakeStore",
		ListDescriber:        DescribeBySubscription(describer.DataLakeStore),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.StorageCache/caches": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.StorageCache/caches",
		ResourceLabel:        "",
		ServiceName:          "StorageCache",
		ListDescriber:        DescribeBySubscription(describer.HpcCache),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_hpc_cache"},
		TerraformServiceName: "hpccache",
		FastDiscovery: false,
	},

	"Microsoft.Batch/batchAccounts": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Batch/batchAccounts",
		ResourceLabel:        "",
		ServiceName:          "Batch",
		ListDescriber:        DescribeBySubscription(describer.BatchAccount),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_batch_account"},
		TerraformServiceName: "batch",
		FastDiscovery: true,
	},

	"Microsoft.Network/networkSecurityGroups": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/networkSecurityGroups",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.NetworkSecurityGroup),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_network_security_group"},
		TerraformServiceName: "network",
		FastDiscovery: true,
	},

	"Microsoft.Authorization/roleDefinitions": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Authorization/roleDefinitions",
		ResourceLabel:        "",
		ServiceName:          "Authorization",
		ListDescriber:        DescribeBySubscription(describer.RoleDefinition),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_role_definition"},
		TerraformServiceName: "authorization",
		FastDiscovery: false,
	},

	"Microsoft.Network/applicationSecurityGroups": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/applicationSecurityGroups",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.NetworkApplicationSecurityGroups),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_application_security_group"},
		TerraformServiceName: "network",
		FastDiscovery: true,
	},

	"Microsoft.Authorization/roleAssignment": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Authorization/roleAssignment",
		ResourceLabel:        "",
		ServiceName:          "Authorization",
		ListDescriber:        DescribeBySubscription(describer.RoleAssignment),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.DocumentDB/MongoDatabases": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DocumentDB/MongoDatabases",
		ResourceLabel:        "",
		ServiceName:          "DocumentDB",
		ListDescriber:        DescribeBySubscription(describer.DocumentDBMongoDatabase),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_cosmosdb_mongo_database"},
		TerraformServiceName: "cosmos",
		FastDiscovery: false,
	},

	"Microsoft.Network/networkWatchers/flowLogs": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/networkWatchers/flowLogs",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.NetworkWatcherFlowLog),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_network_watcher_flow_log"},
		TerraformServiceName: "network",
		FastDiscovery: false,
	},

	"Microsoft.Sql/elasticPools": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Sql/elasticPools",
		ResourceLabel:        "",
		ServiceName:          "Sql",
		ListDescriber:        DescribeBySubscription(describer.SqlServerElasticPool),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_sql_elasticpool"},
		TerraformServiceName: "sql",
		FastDiscovery: true,
	},

	"Microsoft.Security/subAssessments": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Security/subAssessments",
		ResourceLabel:        "",
		ServiceName:          "Security",
		ListDescriber:        DescribeBySubscription(describer.SecurityCenterSubAssessment),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Compute/disks": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/disks",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeDisk),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_managed_disk"},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Devices/iotHubDpses": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Devices/iotHubDpses",
		ResourceLabel:        "",
		ServiceName:          "Devices",
		ListDescriber:        DescribeBySubscription(describer.IOTHubDps),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.HDInsight/clusters": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.HDInsight/clusters",
		ResourceLabel:        "",
		ServiceName:          "HDInsight",
		ListDescriber:        DescribeBySubscription(describer.HdInsightCluster),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_hdinsight_cluster"},
		TerraformServiceName: "hdinsight",
		FastDiscovery: true,
	},

	"Microsoft.ServiceFabric/clusters": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.ServiceFabric/clusters",
		ResourceLabel:        "",
		ServiceName:          "ServiceFabric",
		ListDescriber:        DescribeBySubscription(describer.ServiceFabricCluster),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_service_fabric_cluster"},
		TerraformServiceName: "servicefabric",
		FastDiscovery: true,
	},

	"Microsoft.SignalRService/signalR": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.SignalRService/signalR",
		ResourceLabel:        "",
		ServiceName:          "SignalRService",
		ListDescriber:        DescribeBySubscription(describer.SignalrService),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_signalr_service"},
		TerraformServiceName: "signalr",
		FastDiscovery: false,
	},

	"Microsoft.Storage/blobs": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Storage/blobs",
		ResourceLabel:        "",
		ServiceName:          "Storage",
		ListDescriber:        DescribeBySubscription(describer.StorageBlob),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_storage_blob"},
		TerraformServiceName: "storage",
		FastDiscovery: false,
	},

	"Microsoft.Storage/storageaccounts/blobservices/containers": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Storage/storageaccounts/blobservices/containers",
		ResourceLabel:        "",
		ServiceName:          "Storage",
		ListDescriber:        DescribeBySubscription(describer.StorageContainer),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_storage_container"},
		TerraformServiceName: "storage",
		FastDiscovery: false,
	},

	"Microsoft.Storage/blobServives": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Storage/blobServives",
		ResourceLabel:        "",
		ServiceName:          "Storage",
		ListDescriber:        DescribeBySubscription(describer.StorageBlobService),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Storage/queues": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Storage/queues",
		ResourceLabel:        "",
		ServiceName:          "Storage",
		ListDescriber:        DescribeBySubscription(describer.StorageQueue),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_storage_queue"},
		TerraformServiceName: "storage",
		FastDiscovery: false,
	},

	"Microsoft.ApiManagement/service": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.ApiManagement/service",
		ResourceLabel:        "",
		ServiceName:          "ApiManagement",
		ListDescriber:        DescribeBySubscription(describer.APIManagement),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_api_management"},
		TerraformServiceName: "apimanagement",
		FastDiscovery: false,
	},

	"Microsoft.Compute/disksreadops": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/disksreadops",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeDiskReadOps),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Compute/virtualMachineScaleSets": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/virtualMachineScaleSets",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeVirtualMachineScaleSet),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_windows_virtual_machine_scale_set","azurerm_linux_virtual_machine_scale_set","azurerm_orchestrated_virtual_machine_scale_set"},
		TerraformServiceName: "compute",
		FastDiscovery: true,
	},

	"Microsoft.DataFactory/factoriesDatasets": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DataFactory/factoriesDatasets",
		ResourceLabel:        "",
		ServiceName:          "DataFactory",
		ListDescriber:        DescribeBySubscription(describer.DataFactoryDataset),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_data_factory_dataset_azure_blob","azurerm_data_factory_dataset_binary","azurerm_data_factory_dataset_cosmosdb_sqlapi","azurerm_data_factory_dataset_delimited_text","azurerm_data_factory_dataset_http","azurerm_data_factory_dataset_json","azurerm_data_factory_dataset_mysql","azurerm_data_factory_dataset_parquet","azurerm_data_factory_dataset_postgresql","azurerm_data_factory_dataset_snowflake","azurerm_data_factory_dataset_sql_server_table","azurerm_data_factory_custom_dataset"},
		TerraformServiceName: "datafactory",
		FastDiscovery: false,
	},

	"Microsoft.Authorization/policyDefinitions": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Authorization/policyDefinitions",
		ResourceLabel:        "",
		ServiceName:          "Authorization",
		ListDescriber:        DescribeBySubscription(describer.PolicyDefinition),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Resources/subscriptions/locations": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Resources/subscriptions/locations",
		ResourceLabel:        "",
		ServiceName:          "Resources",
		ListDescriber:        DescribeBySubscription(describer.Location),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Compute/diskAccesses": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/diskAccesses",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeDiskAccess),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_disk_access"},
		TerraformServiceName: "compute",
		FastDiscovery: false,
	},

	"Microsoft.DBforMySQL/servers": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DBforMySQL/servers",
		ResourceLabel:        "",
		ServiceName:          "DBforMySQL",
		ListDescriber:        DescribeBySubscription(describer.MysqlServer),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_mysql_server"},
		TerraformServiceName: "mysql",
		FastDiscovery: true,
	},

	"Microsoft.DBforMySQL/flexibleservers": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DBforMySQL/flexibleservers",
		ResourceLabel:        "",
		ServiceName:          "DBforMySQL",
		ListDescriber:        DescribeBySubscription(describer.MysqlFlexibleservers),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Cache/redisenterprise": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Cache/redisenterprise",
		ResourceLabel:        "",
		ServiceName:          "Cache",
		ListDescriber:        DescribeBySubscription(describer.CacheRedisEnterprise),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.DataLakeAnalytics/accounts": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DataLakeAnalytics/accounts",
		ResourceLabel:        "",
		ServiceName:          "DataLakeAnalytics",
		ListDescriber:        DescribeBySubscription(describer.DataLakeAnalyticsAccount),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Insights/activityLogAlerts": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Insights/activityLogAlerts",
		ResourceLabel:        "",
		ServiceName:          "Insights",
		ListDescriber:        DescribeBySubscription(describer.LogAlert),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Compute/virtualMachineCpuUtilizationHourly": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/virtualMachineCpuUtilizationHourly",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeVirtualMachineCpuUtilizationHourly),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/loadBalancers/outboundRules": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/loadBalancers/outboundRules",
		ResourceLabel:        "",
		ServiceName:          "LoadBalancer",
		ListDescriber:        DescribeBySubscription(describer.LoadBalancerOutboundRule),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_lb_outbound_rule"},
		TerraformServiceName: "loadbalancer",
		FastDiscovery: false,
	},

	"Microsoft.HybridCompute/machines": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.HybridCompute/machines",
		ResourceLabel:        "",
		ServiceName:          "HybridCompute",
		ListDescriber:        DescribeBySubscription(describer.HybridComputeMachine),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_hybrid_compute_machine"},
		TerraformServiceName: "hybridcompute",
		FastDiscovery: false,
	},

	"Microsoft.Network/loadBalancers/inboundNatRules": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/loadBalancers/inboundNatRules",
		ResourceLabel:        "",
		ServiceName:          "LoadBalancer",
		ListDescriber:        DescribeBySubscription(describer.LoadBalancerNatRule),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_lb_nat_rule"},
		TerraformServiceName: "loadbalancer",
		FastDiscovery: false,
	},

	"Microsoft.Resources/providers": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Resources/providers",
		ResourceLabel:        "",
		ServiceName:          "Resources",
		ListDescriber:        DescribeBySubscription(describer.ResourceProvider),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/routeTables": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/routeTables",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.RouteTables),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_route_table"},
		TerraformServiceName: "network",
		FastDiscovery: true,
	},

	"Microsoft.DocumentDB/databaseAccounts": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DocumentDB/databaseAccounts",
		ResourceLabel:        "",
		ServiceName:          "DocumentDB",
		ListDescriber:        DescribeBySubscription(describer.CosmosdbAccount),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_cosmosdb_account"},
		TerraformServiceName: "cosmos",
		FastDiscovery: true,
	},

	"Microsoft.Network/applicationGateways": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/applicationGateways",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.ApplicationGateway),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_application_gateway"},
		TerraformServiceName: "network",
		FastDiscovery: true,
	},

	"Microsoft.Security/automations": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Security/automations",
		ResourceLabel:        "",
		ServiceName:          "Security",
		ListDescriber:        DescribeBySubscription(describer.SecurityCenterAutomation),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_security_center_automation"},
		TerraformServiceName: "securitycenter",
		FastDiscovery: false,
	},

	"Microsoft.Kubernetes/connectedClusters": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Kubernetes/connectedClusters",
		ResourceLabel:        "",
		ServiceName:          "Kubernetes",
		ListDescriber:        DescribeBySubscription(describer.HybridKubernetesConnectedCluster),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.KeyVault/vaults/keys": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.KeyVault/vaults/keys",
		ResourceLabel:        "",
		ServiceName:          "KeyVault",
		ListDescriber:        DescribeBySubscription(describer.KeyVaultKey),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.DBforMariaDB/servers": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DBforMariaDB/servers",
		ResourceLabel:        "",
		ServiceName:          "DBforMariaDB",
		ListDescriber:        DescribeBySubscription(describer.MariadbServer),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_mariadb_server"},
		TerraformServiceName: "mariadb",
		FastDiscovery: true,
	},

	"Microsoft.DBforMariaDB/servers/databases": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DBforMariaDB/servers/databases",
		ResourceLabel:        "",
		ServiceName:          "DBforMariaDB",
		ListDescriber:        DescribeBySubscription(describer.MariadbDatabases),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: true,
	},

	"Microsoft.Compute/disksreadopsdaily": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/disksreadopsdaily",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeDiskReadOpsDaily),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Web/plan": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Web/plan",
		ResourceLabel:        "",
		ServiceName:          "Web",
		ListDescriber:        DescribeBySubscription(describer.AppServicePlan),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_app_service_plan"},
		TerraformServiceName: "web",
		FastDiscovery: false,
	},

	"Microsoft.Compute/disksreadopshourly": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/disksreadopshourly",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeDiskReadOpsHourly),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Compute/diskswriteopsdaily": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/diskswriteopsdaily",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeDiskWriteOpsDaily),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Resources/tenants": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Resources/tenants",
		ResourceLabel:        "",
		ServiceName:          "Resources",
		ListDescriber:        DescribeBySubscription(describer.Tenant),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Network/virtualNetworkGateways": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/virtualNetworkGateways",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.VirtualNetworkGateway),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_virtual_network_gateway"},
		TerraformServiceName: "network",
		FastDiscovery: false,
	},

	"Microsoft.Devices/iotHubs": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Devices/iotHubs",
		ResourceLabel:        "",
		ServiceName:          "Devices",
		ListDescriber:        DescribeBySubscription(describer.IOTHub),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_iothub"},
		TerraformServiceName: "iothub",
		FastDiscovery: false,
	},

	"Microsoft.Logic/workflows": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Logic/workflows",
		ResourceLabel:        "",
		ServiceName:          "Logic",
		ListDescriber:        DescribeBySubscription(describer.LogicAppWorkflow),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_logic_app_workflow"},
		TerraformServiceName: "logic",
		FastDiscovery: false,
	},

	"Microsoft.Sql/flexibleServers": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Sql/flexibleServers",
		ResourceLabel:        "",
		ServiceName:          "Sql",
		ListDescriber:        DescribeBySubscription(describer.SqlServerFlexibleServer),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Resources/links": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Resources/links",
		ResourceLabel:        "",
		ServiceName:          "Resources",
		ListDescriber:        DescribeBySubscription(describer.ResourceLink),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Resources/subscriptions": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Resources/subscriptions",
		ResourceLabel:        "",
		ServiceName:          "Resources",
		ListDescriber:        DescribeBySubscription(describer.Subscription),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_subscription"},
		TerraformServiceName: "subscription",
		FastDiscovery: false,
	},

	"Microsoft.Compute/images": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/images",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeImage),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_image"},
		TerraformServiceName: "compute",
		FastDiscovery: false,
	},

	"Microsoft.Compute/virtualMachines": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/virtualMachines",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeVirtualMachine),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_linux_virtual_machine","azurerm_windows_virtual_machine"},
		TerraformServiceName: "compute",
		FastDiscovery: true,
	},

	"Microsoft.Network/natGateways": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/natGateways",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.NatGateway),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_nat_gateway"},
		TerraformServiceName: "network",
		FastDiscovery: true,
	},

	"Microsoft.Network/loadBalancers/probes": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/loadBalancers/probes",
		ResourceLabel:        "",
		ServiceName:          "LoadBalancer",
		ListDescriber:        DescribeBySubscription(describer.LoadBalancerProbe),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_lb_probe"},
		TerraformServiceName: "loadbalancer",
		FastDiscovery: false,
	},

	"Microsoft.KeyVault/vaults": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.KeyVault/vaults",
		ResourceLabel:        "",
		ServiceName:          "KeyVault",
		ListDescriber:        DescribeBySubscription(describer.KeyVault),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_key_vault"},
		TerraformServiceName: "keyvault",
		FastDiscovery: false,
	},

	"Microsoft.KeyVault/managedHsms": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.KeyVault/managedHsms",
		ResourceLabel:        "",
		ServiceName:          "KeyVault",
		ListDescriber:        DescribeBySubscription(describer.KeyVaultManagedHardwareSecurityModule),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_key_vault_managed_hardware_security_module"},
		TerraformServiceName: "keyvault",
		FastDiscovery: false,
	},

	"Microsoft.KeyVault/vaults/secrets": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.KeyVault/vaults/secrets",
		ResourceLabel:        "",
		ServiceName:          "KeyVault",
		ListDescriber:        DescribeBySubscription(describer.KeyVaultSecret),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_key_vault_secret"},
		TerraformServiceName: "keyvault",
		FastDiscovery: false,
	},

	"Microsoft.AppConfiguration/configurationStores": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.AppConfiguration/configurationStores",
		ResourceLabel:        "",
		ServiceName:          "AppConfiguration",
		ListDescriber:        DescribeBySubscription(describer.AppConfiguration),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Compute/virtualMachineCpuUtilization": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/virtualMachineCpuUtilization",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeVirtualMachineCpuUtilization),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Storage/storageAccounts": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Storage/storageAccounts",
		ResourceLabel:        "",
		ServiceName:          "Storage",
		ListDescriber:        DescribeBySubscription(describer.StorageAccount),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_storage_account"},
		TerraformServiceName: "storage",
		FastDiscovery: true,
	},

	"Microsoft.AppPlatform/Spring": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.AppPlatform/Spring",
		ResourceLabel:        "",
		ServiceName:          "AppPlatform",
		ListDescriber:        DescribeBySubscription(describer.SpringCloudService),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_spring_cloud_service"},
		TerraformServiceName: "springcloud",
		FastDiscovery: false,
	},

	"Microsoft.Compute/galleries": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/galleries",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeGallery),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_shared_image_gallery"},
		TerraformServiceName: "compute",
		FastDiscovery: false,
	},

	"Microsoft.Compute/hostGroups": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/hostGroups",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeHostGroup),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_dedicated_host_group"},
		TerraformServiceName: "compute",
		FastDiscovery: false,
	},

	"Microsoft.Compute/hostGroups/hosts": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/hostGroups/hosts",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeHost),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_dedicated_host"},
		TerraformServiceName: "compute",
		FastDiscovery: false,
	},

	"Microsoft.Compute/restorePointCollections": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/restorePointCollections",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeRestorePointCollection),
		GetDescriber:          nil ,
		TerraformName:        []string{},
		TerraformServiceName: "",
		FastDiscovery: false,
	},

	"Microsoft.Compute/sshPublicKeys": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Compute/sshPublicKeys",
		ResourceLabel:        "",
		ServiceName:          "Compute",
		ListDescriber:        DescribeBySubscription(describer.ComputeSSHPublicKey),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_ssh_public_key"},
		TerraformServiceName: "compute",
		FastDiscovery: false,
	},

	"Microsoft.Cdn/profiles/endpoints": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Cdn/profiles/endpoints",
		ResourceLabel:        "",
		ServiceName:          "Cdn",
		ListDescriber:        DescribeBySubscription(describer.CdnEndpoint),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_cdn_endpoint"},
		TerraformServiceName: "cdn",
		FastDiscovery: false,
	},

	"Microsoft.BotService/botServices": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.BotService/botServices",
		ResourceLabel:        "",
		ServiceName:          "BotService",
		ListDescriber:        DescribeBySubscription(describer.BotServiceBot),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_bot_web_app"},
		TerraformServiceName: "bot",
		FastDiscovery: false,
	},

	"Microsoft.DocumentDB/cassandraClusters": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.DocumentDB/cassandraClusters",
		ResourceLabel:        "",
		ServiceName:          "DocumentDB",
		ListDescriber:        DescribeBySubscription(describer.DocumentDBCassandraCluster),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_cosmosdb_cassandra_cluster"},
		TerraformServiceName: "cosmos",
		FastDiscovery: false,
	},

	"Microsoft.Network/ddosProtectionPlans": {
		Connector:            source.CloudAzure,
		ResourceName:         "Microsoft.Network/ddosProtectionPlans",
		ResourceLabel:        "",
		ServiceName:          "Network",
		ListDescriber:        DescribeBySubscription(describer.NetworkDDoSProtectionPlan),
		GetDescriber:          nil ,
		TerraformName:        []string{"azurerm_network_ddos_protection_plan"},
		TerraformServiceName: "network",
		FastDiscovery: false,
	},
}
