on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    environment:
      name: ${{ github.ref_name }}
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          cache: false
      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          release_branches: main
          tag_prefix: v
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/kaytu-io.insteadOf https://github.com/kaytu-io
      - name: Build azure plugin app
        working-directory: ./steampipe-plugin-azure
        run: make build
      - name: Build azuread plugin app
        working-directory: ./steampipe-plugin-azuread
        run: make build
      - name: Pack azure plugin build
        working-directory: ./steampipe-plugin-azure
        run: |
          tar -cvf build.tar build
      - name: Pack azuread plugin build
        working-directory: ./steampipe-plugin-azuread
        run: |
          tar -cvf build.tar build
      - name: Upload azure plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: steampipe-plugin-azure
          path: ./steampipe-plugin-azure/build.tar
          retention-days: 1
      - name: Upload azuread plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: steampipe-plugin-azuread
          path: ./steampipe-plugin-azuread/build.tar
          retention-days: 1
      - name: Set latest tag output
        id: set_latest_tag
        run: |
          if [[ -z "${{ steps.tag_version.outputs.new_tag }}" ]]; then
            echo "latest_tag=${{ steps.tag_version.outputs.new_tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "latest_tag=${{ steps.tag_version.outputs.previous_tag }}" >> "$GITHUB_OUTPUT"
          fi
  deploy-azure-plugin:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download azure plugin artifact
        uses: actions/download-artifact@v3
        with:
          name: steampipe-plugin-azure
          path: .
      - name: Unpack artifact
        run: |
          tar -xvf build.tar
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/steampipe-plugin-azure:0.0.1
            ${{ vars.DOCKER_REGISTRY }}/steampipe-plugin-azure:0.0.1-${{ github.run_id }}
          file: steampipe-plugin-azure/docker/Dockerfile
          context: .
  deploy-azuread-plugin:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download azuread plugin artifact
        uses: actions/download-artifact@v3
        with:
          name: steampipe-plugin-azuread
          path: .
      - name: Unpack artifact
        run: |
          tar -xvf build.tar
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/steampipe-plugin-azuread:0.0.1
            ${{ vars.DOCKER_REGISTRY }}/steampipe-plugin-azuread:0.0.1-${{ github.run_id }}
          file: steampipe-plugin-azuread/docker/Dockerfile
          context: .
