on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    environment:
      name: ${{ github.ref_name }}
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.set_latest_tag.outputs.latest_tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Install musl cc
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools musl-dev musl
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          cache: false
      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          release_branches: main
          tag_prefix: v
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/kaytu-io.insteadOf https://github.com/kaytu-io
      - name: Build azure plugin app
        working-directory: ./steampipe-plugin-azure
        run: make build
      - name: Build azuread plugin app
        working-directory: ./steampipe-plugin-azuread
        run: make build
      - name: Pack azure plugin build
        working-directory: ./steampipe-plugin-azure
        run: |
          tar -cvf build.tar build
      - name: Pack azuread plugin build
        working-directory: ./steampipe-plugin-azuread
        run: |
          tar -cvf build.tar build
      - name: Upload azure plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: steampipe-plugin-azure
          path: ./steampipe-plugin-azure/build.tar
          retention-days: 1
      - name: Upload azuread plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: steampipe-plugin-azuread
          path: ./steampipe-plugin-azuread/build.tar
          retention-days: 1
      - name: Build lambda describer app
        working-directory: .
        run: make lambda-build
      - name: Pack lambda describer build
        working-directory: .
        run: |
          tar -cvf build.tar build
      - name: Upload lambda describer artifact
        uses: actions/upload-artifact@v3
        with:
          name: kaytu-azure-describer
          path: ./build.tar
          retention-days: 1
      - name: Build az functions describer app
        working-directory: .
        run: make functions-build
      - name: Pack az functions describer build
        working-directory: .
        run: |
          tar -cvf azfunction.tar azfunction
      - name: Upload az functions artifact
        uses: actions/upload-artifact@v3
        with:
          name: azfunction-kaytu-azure-describer
          path: ./azfunction.tar
          retention-days: 1
      - name: Build local describer app
        working-directory: .
        run: make local-build
      - name: Pack local describer build
        working-directory: .
        run: |
          tar -cvf local.tar local
      - name: Upload local artifact
        uses: actions/upload-artifact@v3
        with:
          name: local-kaytu-azure-describer
          path: ./local.tar
          retention-days: 1
      - name: Set latest tag output
        id: set_latest_tag
        run: |
          if [[ -z "${{ steps.tag_version.outputs.new_tag }}" ]]; then
            echo "latest_tag=${{ steps.tag_version.outputs.previous_tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "latest_tag=${{ steps.tag_version.outputs.new_tag }}" >> "$GITHUB_OUTPUT"
          fi
  deploy-azure-plugin:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download azure plugin artifact
        uses: actions/download-artifact@v3
        with:
          name: steampipe-plugin-azure
          path: .
      - name: Unpack artifact
        run: |
          tar -xvf build.tar
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - uses: docker/login-action@v2
        with:
          registry: ${{ vars.AWS_DOCKER_REGISTRY }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: |
            ${{ vars.AWS_DOCKER_REGISTRY }}/steampipe-plugin-azure:0.0.1
            ${{ vars.AWS_DOCKER_REGISTRY }}/steampipe-plugin-azure:${{ needs.build.outputs.latest_tag }}
          file: steampipe-plugin-azure/docker/Dockerfile
          context: .
      - name: Azure Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.AZURE_DOCKER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ vars.AZURE_DOCKER_REGISTRY }}/steampipe-plugin-azure:0.0.1
            ${{ vars.AZURE_DOCKER_REGISTRY }}/steampipe-plugin-azure:${{ needs.build.outputs.latest_tag }}
          file: steampipe-plugin-azure/docker/Dockerfile
          context: .
  deploy-azuread-plugin:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download azuread plugin artifact
        uses: actions/download-artifact@v3
        with:
          name: steampipe-plugin-azuread
          path: .
      - name: Unpack artifact
        run: |
          tar -xvf build.tar
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - uses: docker/login-action@v2
        with:
          registry: ${{ vars.AWS_DOCKER_REGISTRY }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: |
            ${{ vars.AWS_DOCKER_REGISTRY }}/steampipe-plugin-azuread:0.0.1
            ${{ vars.AWS_DOCKER_REGISTRY }}/steampipe-plugin-azuread:${{ needs.build.outputs.latest_tag }}
          file: steampipe-plugin-azuread/docker/Dockerfile
          context: .
      - name: Azure Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.AZURE_DOCKER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ vars.AZURE_DOCKER_REGISTRY }}/steampipe-plugin-azuread:0.0.1
            ${{ vars.AZURE_DOCKER_REGISTRY }}/steampipe-plugin-azuread:${{ needs.build.outputs.latest_tag }}
          file: steampipe-plugin-azuread/docker/Dockerfile
          context: .
  deploy-lambda-describer:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download lambda describer artifact
        uses: actions/download-artifact@v3
        with:
          name: kaytu-azure-describer
          path: .
      - name: Unpack lambda describer artifact
        run: |
          tar -xvf build.tar
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - uses: docker/login-action@v2
        with:
          registry: ${{ vars.AWS_DOCKER_REGISTRY }}
      - name: Build and push Docker images for lambda describer
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: |
            ${{ vars.AWS_DOCKER_REGISTRY }}/kaytu-azure-describer:latest
            ${{ vars.AWS_DOCKER_REGISTRY }}/kaytu-azure-describer:${{ needs.build.outputs.latest_tag }}
          file: Dockerfile
          context: .
      - name: Azure Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.AZURE_DOCKER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ vars.AZURE_DOCKER_REGISTRY }}/kaytu-azure-describer:latest
            ${{ vars.AZURE_DOCKER_REGISTRY }}/kaytu-azure-describer:${{ needs.build.outputs.latest_tag }}
          file: Dockerfile
          context: .
      - name: Configure AWS credentials for uploading lambda
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_FOR_LAMBDA }}
      - name: AWS Lambda Deploy
        run: |
          aws lambda update-function-code --function-name kaytu-azure-describer --image-uri ${{ vars.AWS_DOCKER_REGISTRY }}/kaytu-azure-describer:${{ needs.build.outputs.latest_tag }}
  deploy-azfunction-describer:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download az functions describer artifact
        uses: actions/download-artifact@v3
        with:
          name: azfunction-kaytu-azure-describer
          path: .
      - name: Unpack az functions describer artifact
        run: |
          tar -xvf azfunction.tar
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip az functions folder
        working-directory: ./azfunction
        run: |
          zip -qq -r azfunction.zip .
      - name: Configure Azure credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to function app
        uses: azure/cli@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az functionapp deployment source config-zip -g kaytu-development -n kaytu-azure-describer --src azfunction/azfunction.zip
      - name: Restart function app
        uses: azure/cli@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az functionapp restart -g kaytu-development -n kaytu-azure-describer
  deploy-local-describer:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download plugin artifact
        uses: actions/download-artifact@v3
        with:
          name: local-kaytu-azure-describer
          path: .
      - name: Unpack plugin artifact
        run: |
          tar -xvf local.tar
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - uses: docker/login-action@v2
        with:
          registry: ${{ vars.AWS_DOCKER_REGISTRY }}
      - name: Build and push Docker images for plugin
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: |
            ${{ vars.AWS_DOCKER_REGISTRY }}/kaytu-azure-describer:local-latest
            ${{ vars.AWS_DOCKER_REGISTRY }}/kaytu-azure-describer:local-${{ needs.build.outputs.latest_tag }}
          file: DockerfileLocal
          context: .
      - name: Azure Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.AZURE_DOCKER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ vars.AZURE_DOCKER_REGISTRY }}/kaytu-azure-describer:local-latest
            ${{ vars.AZURE_DOCKER_REGISTRY }}/kaytu-azure-describer:local-${{ needs.build.outputs.latest_tag }}
          file: DockerfileLocal
          context: .